### ISSUE TITLE
Check how many people have registered for a course

### ISSUE THREAD

**Issue by sangeethankumar** [ibehave-ibots/iBOTS-Tools#6]
GIVEN
a course for which 3 people have registered

WHEN
we ask for the number of registrants

THEN
the number of registrants is 3

NOTE: Does this include waitlisted registrants? Does zoom already have a feature for waitlisting registrants?

**Comment by mohammadbashiri** [comment]
Depending on the setting of the meeting we can choose to approve registrants. Basically a waiting list (which answers the above question). 

Importantly, this results in 3 possible statuses of the registrants: `pending`, `approved`, and `denied`. By default when we make a call to `https://api.zoom.us/v2/meetings/{meeting_id}/registrants` only approved registrants are returned, which is the behavior of the current implementation of `get_registrants` since no params are passed to the `get` call. I would suggest changing the behavior such that:
- if a status is specified then the function returns the list of registrants only for that status
- otherwise, it returns a dictionary containing registrants with any status

What do you think? @sangeethankumar @nickdelgrosso 

ref: https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingRegistrants
